### ISSUE TITLE
Support count

### ISSUE THREAD

**Issue by newlix** [jrf0110/dirac#57]
It would be nice to have count support. 
ex.
```javascript
dirac.dals.users.count({ id: { $gt: 5 } }, function(error, count){
  /* ... */
});
```
How to use mo-sql to represent "select Count(*) from users"?

**Comment by jrf0110** [comment]
In mosql:

```javascript
{
  type: 'select'
, table: 'users'
, columns: [{ expression: 'count(*)' }]
, where: { id: { $gt: 5 } }
}
```

**Comment by jrf0110** [comment]
Count would be a nice function. Here's a plugin to support it:

```javascript
/* Before dirac.init(...) */
dirac.DAL = dirac.DAL.extend({
  count: function( where, callback ){
    if ( typeof where === 'function' ){
      callback = where;
      where = {};
    }

    var options = {
      columns: [{ expression: 'count(*)', alias: 'count' }]
    };

    return this.find( where, options, function( error, result ){
      if ( error ) return callback( error );

      return callback( null, result[0].count );
    });
  }
});
```

Then you can do stuff like:

```javascript
dirac.dals.users.count( console.log.bind( console ) );
dirac.dals.users.count( { name: { $ilike: 'bob' } }, console.log.bind( console ) );
```

**Comment by newlix** [comment]
Thank you very much. The solution is so neat. I really love your libraries. They deserve more promotion.
 
Btw, sometime I need to count on a joined table, so I think  the `options` parameter is also necessary.

**Comment by jrf0110** [comment]
@newlix thanks! That means a lot :)

I think if you're doing more complex counts, then you're better off just using the `expression` helper in the columns array

**Comment by jrf0110** [comment]
Also, just a heads up, there will be some big changes come v1.0 https://github.com/jrf0110/dirac/issues/54 put your thoughts there

**Comment by newlix** [comment]
Thank you.

**Comment by newlix** [comment]
How can I do a distinct count ?

**Comment by jrf0110** [comment]
You mean something equivalent to:

```sql
select
  distinct on (organization)
  count(*)
from users
group by organization;
```

**Comment by jrf0110** [comment]
If so, then we can go off our plugin we added up there (assuming we added the options parameter)

```javascript
dirac.dals.users.count( {}, {
  distinct: ['organization']
, groupBy: ['organization']
})
```

Where the second argument will get mixed into the options query

**Comment by newlix** [comment]
But this will return something like [{count:1}, {count:10}, ...] 
I expected we can have 
```sql
SELECT COUNT(DISTINCT column_name) FROM table_name; 
```

**Comment by jrf0110** [comment]
you could do a couple of things. If you're not worried about having a semantic column list, then the expression helper will do what you need:

```javascript
{
  columns: [{ expression: 'count( distinct column_name )' }, ...]
}
```

If you're just wanting something more semantic, you can register a new query type:

```javascript
dirac.db.mosql.registerQueryType(
  'count-distinct'
, 'count( distinct {columns} )
);
```

And do something like:

```javascript
{
  columns: [{ type: 'count-distinct', columns: ['column_name'] }, { ... }]
}
```

Even that's a little crappy.

What would be nice is if we could do this:

```javascript
{
  columns: [{ distinct: 'column_name' }, { distinct: 'column_name2' }, ...]
}
```

Hrmm..
